apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: contrail-analytics-snmp
  namespace: kube-system
  labels:
    app: contrail-analytics-snmp
spec:
  selector:
    matchLabels:
      app: contrail-analytics-snmp
  template:
    metadata:
      labels:
        app: contrail-analytics-snmp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: 'node-role.kubernetes.io/master'
                    operator: Exists
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoSchedule
      hostNetwork: true
      initContainers:
        - name: contrail-node-init
          image: 'hub.juniper.net/contrail/contrail-node-init:2011.138'
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_TYPE
              value: 'analytics-snmp'
            - name: CONTRAIL_STATUS_IMAGE
              value: 'hub.juniper.net/contrail/contrail-status:2011.138'
          envFrom:
            - configMapRef:
                name: env
            - configMapRef:
                name: contrail-analyticsdb-config
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /host/usr/bin
              name: host-usr-bin
            - mountPath: /host/var/lib
              name: host-var-lib
      containers:
        - name: contrail-analytics-snmp-collector
          image: 'hub.juniper.net/contrail/contrail-analytics-snmp-collector:2011.138'
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: env
          volumeMounts:
            - mountPath: /var/log/contrail
              name: analytics-snmp-logs
          env:
            - name: NODE_TYPE
              value: analytics-snmp
        - name: contrail-analytics-snmp-topology
          image: 'hub.juniper.net/contrail/contrail-analytics-snmp-topology:2011.138'
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: env
          volumeMounts:
            - mountPath: /var/log/contrail
              name: analytics-snmp-logs
          env:
            - name: NODE_TYPE
              value: analytics-snmp
        - name: contrail-analytics-snmp-nodemgr
          image: 'hub.juniper.net/contrail/contrail-nodemgr:2011.138'
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: env
            - configMapRef:
                name: nodemgr-config
            - configMapRef:
                name: contrail-analyticsdb-config
          env:
            - name: NODE_TYPE
              value: analytics-snmp
          volumeMounts:
            - mountPath: /var/log/contrail
              name: analytics-snmp-logs
            - mountPath: /mnt
              name: docker-unix-socket
        - name: contrail-analytics-snmp-provisioner
          image: 'hub.juniper.net/contrail/contrail-provisioner:2011.138'
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: env
            - configMapRef:
                name: defaults-env
            - configMapRef:
                name: nodemgr-config
            - configMapRef:
                name: contrail-analyticsdb-config
          env:
            - name: NODE_TYPE
              value: analytics-snmp
          volumeMounts:
            - mountPath: /var/log/contrail
              name: analytics-snmp-logs
      imagePullSecrets:
        - name: contrail-registry
      volumes:
        - name: analytics-snmp-logs
          hostPath:
            path: /var/log/contrail/analytics-snmp
        - name: host-var-lib
          hostPath:
            path: /var/lib
        - name: docker-unix-socket
          hostPath:
            path: /var/run
        - name: host-usr-bin
          hostPath:
            path: /usr/bin
